version: '3'

services:

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:8883"
    volumes:
      - ./site/data/openmoxie.conf:/mosquitto/config/mosquitto.conf
      - ./local/work:/mosquitto/log
      - ./keys:/mosquitto/config/keys
    command: mosquitto -c /mosquitto/config/mosquitto.conf

  openmoxie:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - ./local/work:/app/site/work
    depends_on:
      - mosquitto