
services:

  mqtt:
    build:
      context: ./
      dockerfile: ./mqtt.Dockerfile
    ports:
      - "8883:8883"
    volumes:
      - ./local/work:/mosquitto/log

  openmoxie:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - ./local/work:/app/site/work
    depends_on:
      - mqtt