
services:

  mqtt:
    build:
      context: ./
      dockerfile: ./mqtt.Dockerfile
    image: openmoxie/openmoxie-mqtt:v0.1
    ports:
      - "8883:8883"
    volumes:
      - ./local/work:/mosquitto/log

  server:
    build: .
    image: openmoxie/openmoxie-server:v0.1
    ports:
      - "8001:8000"
    volumes:
      - ./local/work:/app/site/work
    depends_on:
      - mqtt